name: worker_service
description: A flutter package that works for native/web, and allows the creation of workers that offload work into a potentially parallel space
version: 0.5.1
homepage: https://github.com/SunnyApp/worker_service

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  isolate: ^2.0.3
  pedantic:

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
