name: grunt_web_worker_gen
description: Generates web workers
publish_to: 'none'

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  analyzer: ^0.41.2
  build: ^1.6.1
  build_config: ^0.4.5
  build_runner: ^1.11.0
  build_web_compilers: ^2.16.1
  flutter_degen: any
  logging: ^0.11.4
  pedantic: ^1.9.2
  recase: ^3.0.1
  source_gen: ^0.9.10+1
  uri: ^0.11.4
  worker_service: any
dev_dependencies:
  test: ^1.15.7

dependency_overrides:
  flutter_degen:
    path: ../../flutter_degen
  worker_service:
    path: ../
  sunny_dart:
    path: ../../sunny_dart
